spring:
  application:
    name: mytestproject

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    # ОСТАВЬТЕ ПУСТЫМ - все настройки в KafkaConfig

  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    contexts: "default"
    default-schema: "public"
    liquibase-schema: "public"

app:
  kafka:
    enabled: true
    topic:
      employee-bulk-sync: employee-bulk-sync

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.example.mytestproject: DEBUG